

ldap:
    host: ldap://localhost
    bindDN: cn=root,cn=visp
    password: balls

listener:
    host: 10.10.1.42
    port: 65042

tool:
    host: ldap://localhost
    bindDN: cn=root,cn=visp
    password: balls
